services:
  backupfire:
    image: mperon/backupfire:latest
    container_name: backupfire
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      # Mount entire /srv from host into container
      - /srv/volumes/backupfire/data:/app/data
      - /srv/docker/backufire/config:/app/config:ro
      # volumes to backup
      - /srv:/srv:ro
      # Allow running docker CLI against host daemon (only if you need it)
      - /var/run/docker.sock:/var/run/docker.sock
    tmpfs:
      - /tmp

    # Run cron mode (your entrypoint uses this by default, but explicit is nice)
    command: ["cron"]
    networks:
      - web
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

networks:
  web:
    external: true
