#!/usr/bin/env bash
#
# Commands for the application command line

# ---------------------------
# Crontab generator
# ---------------------------

bk_cmd_generate_cron() {
  local cfg_file="$BK_CONFIG" cronstr=
  local key=
  declare -A cron

  # add header comments:
  cat <<EOF
# -------------------------------------
# Crontab for $SCRIPT_NAME
# -------------------------------------
#
# Created At: $(date -u '+%-d, %B %Y at %H:%M:%S UTC')
#  Timestamp: $(date -u '+%Y%m%d%H%M%SUTC')
#
# File was generated by $SCRIPT_NAME, so don't change it manually
# recreate using ./$SCRIPT_NAME -c $BK_CONFIG -C
EOF
  # first, read all sections and get CronJob option
  printf "\n%s\n" "# Crontab of section [General]"
  # read crontab of general
  cronstr="$(fn_ini_get "${cfg_file}" "General" "CronJob")"
  [[ -n "$cronstr" ]] && bk_cmd_crontab_gen_line "$cronstr" "-a"

  # Read all sections of an ini file and generate cron file
  while IFS= read -r sec; do
    # ignore empty sections and protected ones
    [[ -z "${sec}" ]] && continue
    fn_in_array "$sec" "${IGNORE_SECTIONS[@]}" && continue

    # for each section read CronJob if it has:
    cronstr="$(fn_ini_get "${cfg_file}" "${sec}" "CronJob")"
    [[ -z "$cronstr" ]] && continue

    # generating crontab of section
    printf "%s\n" "# Crontab of section [$sec]"
    #tem uma linha
    bk_cmd_crontab_gen_line "$cronstr" "$sec"

  done < <(fn_ini_list_sections "${cfg_file}")

  fn_ini_load_sections cron "$BK_CONFIG" "crontab,Crontab"
  (( ${#cron[@]} > 0 )) && printf "\n%s\n" "# Crontab of section [Crontab]"
  for k in "${!cron[@]}"; do
    key="$k" cronstr="${cron[$k]}"
    [[ -z "$cronstr" ]] && continue
    bk_cmd_crontab_gen_line "$cronstr"
  done
}

bk_cmd_crontab_gen_line() {
  local line="$1" minute= hour= monthday= month= weekday= command=
  shift
  local cmd=() argtasks=("$@") tasks=() targ=
  local firstarg="${argtasks[0]-}"; firstarg="${firstarg//[[:space:]]/}"

  # parse line to ensure it has at least 5
  IFS=' ' read -r minute hour monthday month weekday cmdtasks <<<"$line"

  # generate command
  cmd+=("$SCRIPT_DIR/$SCRIPT_NAME" "-c" "$BK_CONFIG")
  # support arguments
  [[ -n "$BK_EMAIL" ]] && cmd+=("-e" "$BK_EMAIL")
  [[ -n "$F_DEBUG" ]] && cmd+=("-d")

  # now set the tasks to be run
  if [[ "${firstarg}" == "-a" ]] || [[ "${cmdtasks// /}" == "-a" ]]; then
    cmd+=("-a")
  else
    #read tasks passed as argument
    for targ in "${argtasks[@]}"; do
      IFS=' ,' read -r -a arr <<< "${targ:-}"
      (( ${#arr[@]} > 0 )) && tasks+=("${arr[@]}")
    done

    # read tasks in the command line
    IFS=' ,' read -r -a arr <<< "${cmdtasks:-}"
    (( ${#arr[@]} > 0 )) && tasks+=("${arr[@]}")

    if (( ${#tasks[@]} == 0 )); then
      printf "\n%s\n" "################################################"
      printf "%s\n"   "# There is not task defined and it's necessary #"
      printf "%s\n"   "################################################"
      exit 1
    fi
    cmd+=("${tasks[@]}")
  fi

  # rediredt output
  local output='>>/proc/1/fd/1 2>>/proc/1/fd/2'

  # now print to sdout
  printf '%s\t%s\t%s\t%s\t%s\t' \
    "${minute:-*}" "${hour:-*}" "${monthday:-*}" "${month:-*}" "${weekday:-*}"
  printf '%q ' "${cmd[@]}"
  printf '%s ' "$output"
  printf '\n'
}
