# General Options
#	Whatever is defined here will be avaliable for all
# 	actions
#
#[General]
#Sets global email to send the action result
#	Email=josh@gmail.com
#Forces the user to run actions
#	User=marcos
#Uses superuser on all actions
#	Super=N
[General]
# will run all Skip=False jobs
CronJob="0 3 * * *"
Super=N
# limit the number of backup files based on the rules with
# KeepWeekly, KeepDaily, KeepMonthly, KeepYearly
BackupLimit=True
KeepWeekly=10
KeepDaily=30
KeepMonthly=12
KeepYearly=5
# this is the default date format to use in the backup files
DateFormat="%Y%m%d%H%M%S"
# backup files prefix
FilePrefix=bk_
# backup structure, tree will use folder for each time (day, week, month..),
# none will save in a sigle directory
BackupStructure=tree
# Use default remote (rclone) options
RemoteDefaultOpts=True
# Default encrypt key
EncryptKey="ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQD5yaF/0CANeURyZ64ehUBf9ihf3Vc+2P8sPz0SbNgyuHhWgYEl1ipiOY78LrYEO3FhIepJPUrtAPwbP/NrMSICoPTV1xsyGlUXP4CrnhOeIdMm9pPeEu4xqUwpi4M4+2fbXWbdBDWH1ETcA8bjkuVYmfTtzoBnPq8FkLyrp3Wty98u9zEWP0TGsnflTkPOMDpS+ML1s03klHdG1UV/RWYc1c2AjPNmrxVUMW8/NhfkjeiTIm5hU3hsNYsPAyqGj+qzWYdoN96DmLWHfQQ9gHU5GjnvyhLML+kMdyaUDsr+w0ZDH7/6wQcVOiCPFiI6cpdrhKVMf5p8PS4jxbiSC0Jv7mZ7BTnKl3xGVHzsS5qysolE8gqbPBUcn7TrXoIvz35SyaJZRx/vgSFxyONLA2Evww5VWwEyw4Y11rX+yZtSCqIQSjK41rflEXD3ez59t/vIA4LSe3oak/XgnOSqZ9Ye8Frn7Mc6w+Ay/+J8mSYlUxxPiGcqLr2LhvhtVnqlfEPeKzd0UIUzfUC72ZRuzLmvKJkMBMHnXShJs6mDV1so350lEBdaARzFlUKFuB8qFeZUfElbT8eq1Db13Ko+3PXfBl0CMox0vHE9JyjyhAaq9UhlvA0qgWY145sD+gugFVd8Mtn7ARRs+n1RSw6NQdYahfuWd2AA6nfKrxnvJR6m6w=="
# Type=Backup
# DockerLogs Action
#DockerSocket=/var/run/docker.sock #default
## services that the logs will be backed up, default is all
#From=nginx,teste,service3,..

[Database]
Type=Backup
Action=postgres
From=postgres://postgres:mysecretpassword@localhost:5469/invtech_ia
# destination folder
# use tmp:/ to use temp dir that will be deleted after upload
To=./volumes/data/
#To=tmp:/
# Ovewrite default pgdump backup options. Defaults: --format=directory
# --jobs=4 --compress=0 --no-owner --no-privileges --blobs
#DbBackupOpts=
#if set, will create a file extension (for --format=custom for example).
# for directory, disable extension and will create a folder.
#DbFileExtension=
Compression=tar.gz
Encrypt=True
#EncryptKey="" # use default
EncryptKeyFile=""
#Remote=pcloud:/BackupFire/
Remote=
Skip=False

[VirtualMachines]
Type=Backup
Action=CopyFiles
From=./volumes/uploads/

#CopyOptions='-Cravzp'
To=./volumes/data/
#To=tmp:/
Compression=tar.gz
#EncryptKey= # use default
Encrypt=True
EncryptKeyFile=
Remote=
#Remote=pcloud:/BackupFire/
Skip=
CronJob=30 2 * * *

[DockerLogs]
Type=Backup
Action=DockerLogs
From=all
To=./volumes/data/
#To=tmp:/
Compression=tar.gz
Encrypt=True
#EncryptKey= # use default
EncryptKeyFile=
Remote=pcloud:/BackupFire/
Skip=

[VPS_Volumes]
Type=Backup
Action=CopyFiles
From=./volumes
Includes="pgdata/,.git"
To=./dist
Compression=tar.gz
Encrypt=False
#Remote=pcloud:/Backups/VPS_Volumes
Skip=
