[General]
CronJob="0 3 * * *"
Super=N
BackupLimit=True
KeepWeekly=10
KeepDaily=30
KeepMonthly=12
KeepYearly=5
DateFormat="%Y%m%d%H%M%S"
FilePrefix=bk_
BackupStructure=tree
RemoteDefaultOpts=True
EncryptKey="ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQD5yaF/0CANeURyZ64ehUBf9ihf3Vc+2P8sPz0SbNgyuHhWgYEl1ipiOY78LrYEO3FhIepJPUrtAPwbP/NrMSICoPTV1xsyGlUXP4CrnhOeIdMm9pPeEu4xqUwpi4M4+2fbXWbdBDWH1ETcA8bjkuVYmfTtzoBnPq8FkLyrp3Wty98u9zEWP0TGsnflTkPOMDpS+ML1s03klHdG1UV/RWYc1c2AjPNmrxVUMW8/NhfkjeiTIm5hU3hsNYsPAyqGj+qzWYdoN96DmLWHfQQ9gHU5GjnvyhLML+kMdyaUDsr+w0ZDH7/6wQcVOiCPFiI6cpdrhKVMf5p8PS4jxbiSC0Jv7mZ7BTnKl3xGVHzsS5qysolE8gqbPBUcn7TrXoIvz35SyaJZRx/vgSFxyONLA2Evww5VWwEyw4Y11rX+yZtSCqIQSjK41rflEXD3ez59t/vIA4LSe3oak/XgnOSqZ9Ye8Frn7Mc6w+Ay/+J8mSYlUxxPiGcqLr2LhvhtVnqlfEPeKzd0UIUzfUC72ZRuzLmvKJkMBMHnXShJs6mDV1so350lEBdaARzFlUKFuB8qFeZUfElbT8eq1Db13Ko+3PXfBl0CMox0vHE9JyjyhAaq9UhlvA0qgWY145sD+gugFVd8Mtn7ARRs+n1RSw6NQdYahfuWd2AA6nfKrxnvJR6m6w=="
# Notifications
NotifyTelegram=True
NotifyEmail=True
TelegramToken=
TelegramChatId=
NotifyFailed=True   # set to false to disable
NotifySuccess=True # set to false to disable
NotifyEmailTo=marcosperon@gmail.com

[Database]
Type=Backup
Action=postgres
From=postgres://postgres:mysecretpassword@backupfire-db:5432/invtech_ia
To=/app/data/
Compression=tar.gz
Encrypt=True
EncryptKeyFile=""
Remote=
Skip=False

[VirtualMachines]
Type=Backup
Action=CopyFiles
From=/app/sources/uploads/
To=/app/data/
Compression=tar.gz
Encrypt=True
EncryptKeyFile=
Remote=
Skip=
CronJob=30 2 * * *

[DockerLogs]
Type=Backup
Action=DockerLogs
From=all
To=/app/data/
Compression=tar.gz
Encrypt=True
EncryptKeyFile=
Remote=
Skip=
